---
- name: Import Flow-Fusion Project Playbooks - Resgister RHEL
  import_playbook: projects/flow-fusion/register.yml
- name: Import Flow-Fusion Project Playbooks - Update packages
  import_playbook: projects/flow-fusion/update.yml
- name: Import Flow-Fusion Project Playbooks - Database
  import_playbook: projects/flow-fusion/database.yml
