---
- name: Manage Database
  hosts: tm-demo-vm-flow-fusion-db
  gather_facts: true
  become: true

  vars: []

  tasks:

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb
        state: present

    