---
- name: Manage Database
  hosts: tm-demo-vm-flow-fusion-db
  gather_facts: true
  become: true

  vars: []

  tasks:

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb-server
        state: latest

    - name: Start MariaDB now and on boot
      ansible.builtin.systemd:
        name: mariadb-server
        state: started
        enabled: true

    - name: Allow access to MariaDB through local firewall
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
