---
- name: Manage Database
  hosts: tm-demo-vm-flow-fusion-db
  gather_facts: true
  become: true

  vars:
    project_code_name: flow-fusion
    project_state: present
    mysql_root_password: "root"
    db_password: "redhat"

  tasks:

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb.x86_64
        state: latest

    - name: Start MariaDB now and on boot
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    - name: Allow access to MariaDB through local firewall
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled

    - name: Install python packages
      ansible.builtin.pip:
        name:
          - PyMySQL
      become: false

    - name: Create the MariaDB database
      command: >
          mysql -u root -p{{ mysql_root_password }} -e "CREATE DATABASE IF NOT EXISTS {{ project_code_name }};"
      no_log: true

    - name: Erstelle den MariaDB-Benutzer
      command: >
        mysql -u root -p{{ mysql_root_password }} -e "CREATE USER IF NOT EXISTS '{{ project_code_name }}_user'@'%' IDENTIFIED BY '{{ db_password }}';"
      no_log: true

    - name: Gewähre dem Benutzer alle Rechte auf die Datenbank
      command: >
        mysql -u root -p{{ mysql_root_password }} -e "GRANT ALL PRIVILEGES ON {{ project_code_name }}.* TO '{{ db_user }}'@'%';"
      no_log: true

    - name: Rechte neu laden
      command: >
        mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES;"
      no_log: true
